name: Generate DSL Diagrams

on:
  push:
    paths:
      - 'diagram/c4-diagram.dsl'
  workflow_dispatch:

jobs:
  generate-dsl-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download Structurizr CLI
        run: |
          wget https://github.com/structurizr/cli/releases/download/v1.28.0/structurizr-cli.zip
          unzip structurizr-cli.zip -d structurizr-cli

      - name: Generate all diagrams (PlantUML)
        run: |
          mkdir -p diagram/output
          java -jar structurizr-cli/structurizr-cli.jar export -workspace diagram/c4-diagram.dsl -format plantuml -output diagram/output

      - name: Generate SVG from PlantUML
        run: |
          curl -o plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.2/plantuml-1.2024.2.jar
          java -jar plantuml.jar -tsvg diagram/output/c4-diagram.puml -o diagram/output

      - name: Commit and push generated diagrams
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add diagram/output/
          git commit -m "docs: Auto-generated diagrams from DSL"
          git push
