name: Generate UML Diagram

on:
  push:
    paths:
      - 'diagram/class-diagram.puml'
  workflow_dispatch:

jobs:
  generate-diagram:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Download PlantUML
        run: |
          curl -o plantuml.jar https://github.com/plantuml/plantuml/releases/download/v1.2024.2/plantuml-1.2024.2.jar

      - name: Generate diagram SVG
        run: |
          java -jar plantuml.jar -tsvg diagram/class-diagram.puml -o diagram

      - name: Commit and push updated diagram
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add diagram/classDiagram.svg
          git commit -m "docs: Auto-update UML diagram"
          git push
